/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Controller.ParameterState;
import Controller.ParametersController;
import Controller.UiController;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.DefaultListModel;

/**
 *
 * @author Bryan Hernandez
 */
public class AddMailbox extends javax.swing.JFrame {

    /**
     * Creates new form AddMailbox
     */
    
    private UiController controller;
    private DefaultListModel processesList;
    private Set<String> processesText;

    public AddMailbox(UiController pController) {
        this.controller = pController;
        processesList  = new DefaultListModel();
        processesText = new HashSet<String>();
        
        for(Model.Process p: this.controller.getController().getProcesses()){
            System.out.println(p.toString() + " 41");
            processesList.addElement(p.toString());
            System.out.println(p.getId() + " : this is a Process");
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(processesList);
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 34, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(70, 30, 200, 20);

        jButton1.setText("Add Mailbox");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 340, 210, 23);

        /*
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        */
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 80, 100, 130);

        jLabel2.setText("Process");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 100, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 220, 166, 96);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.controller.getController().addMailbox(new Model.Mailbox(this.jTextField1.getText()));
        String s = "";
        Iterator iterator = processesText.iterator();
        while(iterator.hasNext()){
            s = (String)iterator.next();
            if(!s.equals("")){
                this.controller.getController().getMailbox(this.jTextField1.getText())
                .addProcessReceive(this.controller.getController().getProcess(s));
            }
        }
        this.jTextField1.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if(ParametersController.getAddressing_Receive()==ParameterState.Addr_Indirect_Static){
            processesText.clear();
            processesText.add(this.jList1.getSelectedValue());
        }
        else{
            processesText.add(this.jList1.getSelectedValue());
        }
        
        String s = "";
        String toPrint = "";
        Iterator iterator = processesText.iterator();
        while(iterator.hasNext()){
            s = (String)iterator.next();
            toPrint = toPrint + s + ",";
        }
        this.jTextArea1.setText(toPrint);
        System.out.println(processesText);
        
    }//GEN-LAST:event_jList1ValueChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
