/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Controller.UiController;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kenneth
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    
    private UiController controller;
    
    public Window(UiController pController) {
        controller = pController;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_monitor = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        combo_processesSelected = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_command = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_allprocesses = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_selectedprocesses1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        txt_monitor.setColumns(20);
        txt_monitor.setRows(5);
        jScrollPane4.setViewportView(txt_monitor);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(350, 290, 310, 157);

        jLabel6.setText("Process");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(343, 50, 37, 14);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(586, 46, 67, 23);

        combo_processesSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                combo_processesSelectedMouseEntered(evt);
            }
        });
        combo_processesSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_processesSelectedActionPerformed(evt);
            }
        });
        getContentPane().add(combo_processesSelected);
        combo_processesSelected.setBounds(388, 46, 192, 22);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Processes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 11, 92, 24);

        jLabel5.setText("Monitor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 270, 36, 14);

        jLabel9.setText("All Processes");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 75, 62, 14);
        getContentPane().add(txt_command);
        txt_command.setBounds(53, 47, 216, 20);

        txt_allprocesses.setColumns(20);
        txt_allprocesses.setRows(5);
        jScrollPane3.setViewportView(txt_allprocesses);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 95, 327, 157);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(275, 46, 57, 23);

        jLabel10.setText("Selected Process");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(343, 75, 81, 14);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 110, 150);

        jLabel7.setText("Execute");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 50, 39, 14);

        txt_selectedprocesses1.setColumns(20);
        txt_selectedprocesses1.setRows(5);
        jScrollPane5.setViewportView(txt_selectedprocesses1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(343, 95, 310, 157);

        jLabel8.setText("Queues");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 270, 37, 14);

        jMenu1.setText("File");

        jMenuItem1.setText("Open batch file..");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("About");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = this.txt_command.getText();
        this.txt_allprocesses.setText("");
        this.controller.sendCommand(str);
        this.controller.updateAll(txt_allprocesses);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String processSelected = this.combo_processesSelected.getItemAt(combo_processesSelected.getSelectedIndex());
        this.controller.updateTextField(this.txt_monitor, this.controller.getLogOf(processSelected).toString());
    }//GEN-LAST:event_btn_updateActionPerformed

    private void combo_processesSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_processesSelectedActionPerformed
        String processSelected = this.combo_processesSelected.getItemAt(combo_processesSelected.getSelectedIndex());
        this.controller.updateTextField(this.txt_monitor, this.controller.getLogOf(processSelected).toString());
        this.controller.updateAll(this.txt_allprocesses);
    }//GEN-LAST:event_combo_processesSelectedActionPerformed

    private void combo_processesSelectedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_processesSelectedMouseEntered
        for(String str : this.controller.getController().getProcessesStringArrayList()){
            if(((DefaultComboBoxModel) this.combo_processesSelected.getModel()).getIndexOf(str) == -1){
                this.combo_processesSelected.addItem(str);
            }
        }
    }//GEN-LAST:event_combo_processesSelectedMouseEntered

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Batch files *.btc", "btc"));
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String selectedFile = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                String contents = new String(Files.readAllBytes(Paths.get(selectedFile)));
                this.controller.sendCommand(contents);
            } catch (IOException ex) {}
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void setMonitorText(String text){
        this.txt_monitor.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_processesSelected;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txt_allprocesses;
    private javax.swing.JTextField txt_command;
    private javax.swing.JTextArea txt_monitor;
    private javax.swing.JTextArea txt_selectedprocesses1;
    // End of variables declaration//GEN-END:variables
}
