/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Controller.UiController;
import Model.Logger;
import Model.Mailbox;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kenneth
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    
    private UiController controller;
    private DefaultListModel queueList;
    private DefaultListModel processesList;
    private DefaultListModel printerList;
 
    public Window(UiController pController) {
        controller = pController;
        queueList = new DefaultListModel();
        processesList  = new DefaultListModel();
        printerList  = new DefaultListModel();
        
        for(Mailbox q: this.controller.getController().getMailboxes()){
            queueList.addElement(q.toString());
            System.out.println(q.getId() + " : this is a Mailbox and has " + q.getReceiveprocess().size() + " processes inside.");
           
        }
        
        for(Model.Process p: this.controller.getController().getProcesses()){
            System.out.println(p.toString() + " 41");
            processesList.addElement(p.toString());
            System.out.println(p.getId() + " : this is a Process");
        }
        
        for(Model.Process p: this.controller.getController().getProcesses()){
            System.out.println(p.toString() + " 41");
            processesList.addElement(p.toString());
            System.out.println(p.getId() + " : this is a Process");
        }
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_monitor = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_command = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_allprocesses = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_mailboxes = new javax.swing.JList<>(queueList);
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_selectedprocesses1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_processes = new javax.swing.JList<>(processesList);
        btn_update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        checkbox_selected = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        list_printers = new javax.swing.JList<>(processesList);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menu_printQueue = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jRadioButton1.setText("jRadioButton1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu2.setText("File");
        jMenuBar3.add(jMenu2);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(null);

        txt_monitor.setColumns(20);
        txt_monitor.setRows(5);
        jScrollPane4.setViewportView(txt_monitor);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(390, 290, 310, 157);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Processes");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 11, 92, 24);

        jLabel5.setText("Monitor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 270, 90, 14);

        jLabel9.setText("All Processes");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 75, 62, 14);
        getContentPane().add(txt_command);
        txt_command.setBounds(53, 47, 216, 20);

        txt_allprocesses.setColumns(20);
        txt_allprocesses.setRows(5);
        jScrollPane3.setViewportView(txt_allprocesses);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 95, 360, 157);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(275, 46, 90, 23);

        jLabel10.setText("Selected Process");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 80, 81, 14);

        /*
        list_mailboxes.setModel(queueList);
        */
        System.out.println(list_mailboxes.getModel().toString() + " : Mailboxes");
        list_mailboxes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_mailboxesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_mailboxes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 90, 150);

        jLabel7.setText("Execute");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 50, 39, 14);

        txt_selectedprocesses1.setColumns(20);
        txt_selectedprocesses1.setRows(5);
        jScrollPane5.setViewportView(txt_selectedprocesses1);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(390, 100, 310, 157);

        jLabel8.setText("Queues");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 270, 80, 14);

        jLabel11.setText("Processes");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 270, 80, 14);

        /*
        list_processes.setModel(queueList);
        */
        System.out.println(list_mailboxes.getModel().toString() + " : Process");
        list_processes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_processesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(list_processes);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(130, 290, 100, 150);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(280, 20, 80, 23);

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 40, 120, 23);

        checkbox_selected.setText("Selected Process");
        getContentPane().add(checkbox_selected);
        checkbox_selected.setBounds(560, 10, 130, 23);

        jLabel12.setText("Printers");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 270, 80, 14);

        /*
        list_printers.setModel(queueList);
        */
        System.out.println(list_mailboxes.getModel().toString() + " : Process");
        list_printers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_printersValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(list_printers);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(250, 290, 100, 150);

        jMenu1.setText("File");

        jMenuItem1.setText("Print Queue");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("View");

        menu_printQueue.setText("Print Queue");
        menu_printQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_printQueueActionPerformed(evt);
            }
        });
        jMenu7.add(menu_printQueue);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("About");

        jMenuItem2.setText("Help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String str = this.txt_command.getText();
        this.txt_allprocesses.setText("");
        this.controller.sendCommand(str);
        this.controller.updateAll(txt_allprocesses);
        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Batch files *.btc", "btc"));
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String selectedFile = fileChooser.getSelectedFile().getAbsolutePath();
            try {
                String contents = new String(Files.readAllBytes(Paths.get(selectedFile)));
                this.controller.sendCommand(contents);
            } catch (IOException ex) {}
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void list_mailboxesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_mailboxesValueChanged
        // TODO add your handling code here:
        this.txt_monitor.setText(this.controller.getController().getMailbox(this.list_mailboxes.getSelectedValue()).getMessages());
    }//GEN-LAST:event_list_mailboxesValueChanged

    private void list_processesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_processesValueChanged
        // TODO add your handling code here:
        this.txt_selectedprocesses1.setText(Logger.getInstance().getProcessLogs(this.list_processes.getSelectedValue()));
    }//GEN-LAST:event_list_processesValueChanged

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        update();
        
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void menu_printQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_printQueueActionPerformed
        // TODO add your handling code here:
        new PrinterStatus(this, true).setVisible(true);
    }//GEN-LAST:event_menu_printQueueActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");   

        int result = fileChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String fileToSave = fileChooser.getSelectedFile().getAbsolutePath() + ".printed";
            try {
                BufferedWriter writer;
                writer = new BufferedWriter(new FileWriter(fileToSave));
                
                if(this.checkbox_selected.isSelected()){
                    writer.write(this.txt_selectedprocesses1.getText());
                }
                else{
                    writer.write(this.txt_allprocesses.getText());
                }
                    
                writer.close();
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void list_printersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_printersValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list_printersValueChanged

    public void setMonitorText(String text){
        this.txt_monitor.setText(text);
    }
    
    public void update(){
        this.txt_allprocesses.setText(Logger.getInstance().getAllLogs());
        this.txt_selectedprocesses1.setText(Logger.getInstance().getProcessLogs(this.list_processes.getSelectedValue()));
        this.txt_monitor.setText(this.controller.getController().getMailbox(this.list_mailboxes.getSelectedValue()).getMessages());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JCheckBox checkbox_selected;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<String> list_mailboxes;
    private javax.swing.JList<String> list_printers;
    private javax.swing.JList<String> list_processes;
    private javax.swing.JMenu menu_printQueue;
    private javax.swing.JTextArea txt_allprocesses;
    private javax.swing.JTextField txt_command;
    private javax.swing.JTextArea txt_monitor;
    private javax.swing.JTextArea txt_selectedprocesses1;
    // End of variables declaration//GEN-END:variables
}
